---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - networkvalidators
  - validationresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - networkvalidators/finalizers
  verbs:
  - update
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - networkvalidators/status
  - validationresults/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch