apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-auth-rolebinding
  labels:
    app.kubernetes.io/instance: metrics-auth-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: validator-plugin-network
    app.kubernetes.io/part-of: validator-plugin-network
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-auth-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
