apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: validator-plugin-network
    app.kubernetes.io/part-of: validator-plugin-network
    app.kubernetes.io/managed-by: kustomize
  name: metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
