# permissions for end users to edit networkvalidators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: networkvalidator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: validator-plugin-network
    app.kubernetes.io/part-of: validator-plugin-network
    app.kubernetes.io/managed-by: kustomize
  name: networkvalidator-editor-role
rules:
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - networkvalidators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - networkvalidators/status
  verbs:
  - get
