apiVersion: validation.spectrocloud.labs/v1alpha1
kind: NetworkValidator
metadata:
  name: network-validator-http-file-cert-secret
spec:
  httpFileRules:
  - name: File on server using custom CA cert (expect non-200)
    paths:
    - https://toolbox.palette-adv.spectrocloud.com:5001
  caCerts:
    secretRefs:
    - name: ca-cert-secret
      key: ca.crt