apiVersion: validation.spectrocloud.labs/v1alpha1
kind: NetworkValidator
metadata:
  name: network-validator-http-file-auth-inline
spec:
  httpFileRules:
  - name: protected-files
    auth:
      basic:
        username: demo-user
        password: demo-pass
    paths:
    - https://software-private.demo.com/release/1.0.0/charts.zip
