apiVersion: validation.spectrocloud.labs/v1alpha1
kind: NetworkValidator
metadata:
  name: network-validator-http-file-basic-auth-secret
spec:
  httpFileRules:
  - name: protected-files
    authSecretRef:
      name: http-creds
      usernameKey: myCustomUsername
      passwordKey: password
    paths:
    - https://software-private.demo.com/release/1.0.0/charts.zip
