resources:
- ../default

images:
- name: quay.io/validator-labs/validator-plugin-network:latest
  newTag: dev

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        control-plane: controller-manager
      name: controller-manager
      namespace: validator-plugin-network-system
    spec:
      template:
        spec:
          containers:
          - name: manager
            args:
            - while true; do sleep 30; done;
            command:
            - /bin/bash
            - -c
            - --
            imagePullPolicy: Always
            resources: null
            livenessProbe: null
            readinessProbe: null
            securityContext: null
          securityContext: null
